[build]
  # Your existing build settings (if any) would go here
  
  # This ignore pattern ensures changes to Python scripts don't trigger rebuilds
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!src/aaWolfWiseETL/'"

[build.processing]
  skip_processing = false

# You can also explicitly exclude the directory from processing
[[redirects]]
  from = "/src/aaWolfWiseETL/*"
  to = "/404.html"
  status = 404
  force = true 