[build]
  # Use our custom Node.js build script to bypass Python detection
  command = "node ./builder.js"
  publish = "dist"
  
  # Force Node.js environment only, configure mise
  environment = { 
    NETLIFY_USE_PYTHON = "false", 
    NODE_VERSION = "18", 
    SKIP_PYTHON_SETUP = "true",
    PYTHON_DISABLE = "true",
    MISE_NODE_VERSION = "18",
    MISE_PYTHON_DISABLE = "true"
  }

# Load our custom build plugin to bypass Python
[[plugins]]
  package = "./netlify-build-plugins/python-bypass"

# Tell Netlify not to process anything Python-related
[build.processing.html]
  pretty_urls = true
  
[build.processing]
  skip_processing = false
  
[functions]
  # Specify the functions directory if you have any
  directory = "functions"

# Ignore changes to Python scripts
[ignore]
  files = ["src/_python_scripts/**/*", "**/*.py", "**/*requirements.txt", "**/Pipfile", "**/Pipfile.lock"]

# Exclude Python directory from processing
[[redirects]]
  from = "/src/_python_scripts/*"
  to = "/404.html"
  status = 404
  force = true

# Block Python files from being served
[[headers]]
  for = "/src/_python_scripts/*"
    [headers.values]
    X-Robots-Tag = "noindex"
    Content-Type = "text/plain" 