[build]
  # Explicitly set the build command to use Node/npm
  command = "npm run build"
  publish = "dist"
  
  # Disable Python processing entirely
  environment = { NETLIFY_USE_PYTHON = "false", NODE_VERSION = "18" }

# Ignore changes to Python scripts
[ignore]
  files = ["src/aaWolfWiseETL/**/*"]

# Exclude Python directory from processing
[[redirects]]
  from = "/src/aaWolfWiseETL/*"
  to = "/404.html"
  status = 404
  force = true

# Block Python files from being served
[[headers]]
  for = "/src/aaWolfWiseETL/*"
    [headers.values]
    X-Robots-Tag = "noindex"
    Content-Type = "text/plain" 